version: "3.8"

services:
  web:
    container_name: "sukeba_api"
    build: .
    volumes:
      - ./backend/api:/code/api
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: "sukeba_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sukeba

volumes:
  postgres_data:
